export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const START_SESION = 'START_SESION';

export const UPDATE_USER = 'UPDATE_USER';

export const GET_ESTABLISHMENT_BY_OWNER = 'GET_ESTABLISHMENT_BY_OWNER';
export const SET_SELECTED_ESTABLISHMENT = 'SET_SELECTED_ESTABLISHMENT';
export const GET_FIELDS_BY_ESTABLISHMENT = 'GET_FIELDS_BY_ESTABLISHMENT';
export const GET_TYPE_OF_SPORTS = 'GET_TYPE_OF_SPORTS';
export const GET_TYPE_OF_GROUNDS = 'GET_TYPE_OF_GROUNDS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SERVICES = 'GET_SERVICES';
export const CREATE_FIELD = 'CREATE_FIELD';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const ERROR_CREATING_FIELD = 'ERROR_CREATING_FIELD';
export const ERROR_DELETING_FIELD = 'ERROR_DELETING_FIELD';
export const ERROR_UPDATE_FIELD = 'ERROR_UPDATE_FIELD';
export const REMOVE_ALERT_MESSAGE = "REMOVE_ALERT_MESSAGE";
export const SET_SELECTED_FIELD = 'SET_SELECTED_FIELD';
export const CREATE_ESTABLISHMENT = 'CREATE_ESTABLISHMENT';
export const UPDATE_ESTABLISHMENT = 'UPDATE_ESTABLISHMENT';
export const ERROR_CREATING_ESTABLISHMENT = 'ERROR_CREATING_ESTABLISHMENT';
export const ERROR_UPDATING_ESTABLISHMENT = 'ERROR_UPDATING_ESTABLISHMENT';
export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const GET_FIELDS = 'GET_FIELDS';


