export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const START_SESION = 'START_SESION';

export const GET_ESTABLISHMENT_BY_OWNER = 'GET_ESTABLISHMENT_BY_OWNER';

export const GET_FIELDS_BY_ESTABLISHMENT = 'GET_FIELDS_BY_ESTABLISHMENT';




